In [3]:
import pandas as pd
import numpy

In [9]:
df = pd.read_csv("./dataset/Agora.csv", encoding="latin1")
df

,Vendor,Category,Item,Item Description,Price,Origin,Destination,Rating,Remarks
0,CheapPayTV,Services/Hacking,12 Month HuluPlus gift Code,12-Month HuluPlus Codes for $25. They are wort...,0.05027025666666667 BTC,Torland,NaN,4.96/5,NaN
1,CheapPayTV,Services/Hacking,Pay TV Sky UK Sky Germany HD TV and much mor...,Hi we offer a World Wide CCcam Service for En...,0.152419585 BTC,Torland,NaN,4.96/5,NaN
2,KryptykOG,Services/Hacking,OFFICIAL Account Creator Extreme 4.2,Tagged Submission Fix Bebo Submission Fix Adju...,0.007000000000000005 BTC,Torland,NaN,4.93/5,NaN
3,cyberzen,Services/Hacking,VPN > TOR > SOCK TUTORIAL,How to setup a VPN > TOR > SOCK super safe enc...,0.019016783532494728 BTC,NaN,NaN,4.89/5,NaN
4,businessdude,Services/Hacking,Facebook hacking guide,. This guide will teach you how to hack Faceb...,0.062018073963963936 BTC,Torland,NaN,4.88/5,NaN
...,...,...,...,...,...,...,...,...,...
109684,gonz324,Drugs/Opioids/Opium,1 gr purified Opium,This Listing is for a gramm of redefined Opium...,0.14363729 BTC,Germany,NaN,4.91/5,NaN
109685,cheqdropz,Weapons/Fireworks,Shipping Ticket,in order for me to ship one of the guns you bo...,0.08680555 BTC,USA,NaN,[0 deals],NaN
109686,SnowQueen,Drugs/Opioids/Opium,0.50 GRAMS #4 White Afghani Heroin - FULL ESCROW,0.50 grams #4 White Afghani Heroin SnowQueen...,0.33641201 BTC,Canada,Worldwide,[0 deals],NaN
109687,SnowQueen,Drugs/Opioids/Opium,1.0 GRAMS #4 White Afghani Heroin - FULL ESCROW,1.0 grams #4 White Afghani Heroin SnowQueen ...,0.61165820 BTC,Canada,Worldwide,[0 deals],NaN
109688,daydreamer,Drugs/Opioids/Opium,HEROIN STAMP BAG (10pcs) BUNDLE,HEROIN STAMP BAG (10pcs) BUNDLE BEST AVAIL...,0.25491129 BTC,USA,NaN,4.87/5,NaN

In [15]:
df2 = pd.read_excel("./dataset/mastersr2.xlsx")
df2

,Title,Sellerid,PriceUSD,PriceBTC,Rating,Reviews,Origin,Destination,Category,Subcategory,Market,Date
0,Ray Ban Tech RB3460 001 Aviator/Flip Out/ Sung...,FoxyGirl,61.161542,0.098232,NaN,NaN,China,Worldwide,Apparel,NaN,SilkRoad2,2014-07-17
1,Ray Ban RB3025 Aviator Classic Sunglasses Replica,FoxyGirl,37.962594,0.060972,NaN,NaN,China,Worldwide,Apparel,NaN,SilkRoad2,2014-07-17
2,Rolex - Watch Box (AAA Grade Replica),RepAAA,100.429777,0.161301,NaN,NaN,"Hong Kong, (China)",Worldwide,Apparel,NaN,SilkRoad2,2014-07-17
3,Ray Ban RB3016 - W0365 | Clubmaster Sunglasses...,FoxyGirl,45.343794,0.072827,NaN,NaN,China,Worldwide,Apparel,NaN,SilkRoad2,2014-07-17
4,Rolex - Submariner 2Tone YG/SS Black [Replica],RepAAA,149.635082,0.24033,NaN,NaN,"Hong Kong, (China)",Worldwide,Apparel,NaN,SilkRoad2,2014-07-17
...,...,...,...,...,...,...,...,...,...,...,...,...
618855,"Twitter , Facebook , youtube , instagram services",profesorhouse,405.582135,1.05,4.80,0.0,Belgium,Undeclared,Services,NaN,SilkRoad2,2014-09-30
618856,"500,000 High Retention Views | YouTube |",SideAlley,224.592459,0.581441,3.65,0.0,Undeclared,Undeclared,Services,NaN,SilkRoad2,2014-09-30
618857,25 000 Real Twitter Followers!,profesorhouse,112.296423,0.290721,4.80,0.0,Belgium,Undeclared,Services,NaN,SilkRoad2,2014-09-30
618858,"40,000 Facebook Followers Subscribers. >Cheap<",SideAlley,77.003052,0.199351,3.65,0.0,Undeclared,Undeclared,Services,NaN,SilkRoad2,2014-09-30
618859,2000 Youtube Real Likes!,profesorhouse,112.296423,0.290721,4.80,0.0,Belgium,Undeclared,Services,NaN,SilkRoad2,2014-09-30